### ISSUE TITLE
Filename mismatch for 2022-04-24 and 2022-05-05

### ISSUE THREAD

**Issue by EvanHong99** [TheQuantPy/youtube-tutorials#1]
I really appreciate your dedicated work and I've learned a lot from your notebooks. 

But I find some filenames are mismatched with the titles of the notebooks.

It will be better if you can correct them. Thanks again for your work!

**Comment by TheQuantPy** [comment]
Really appreciate the comment, let me know of any others that you find. I have fixed this one
